[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn app_tarea:app --host 0.0.0.0 --port $PORT"
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 300
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 2
